title: Sophie Lin # your name (or website title) here
logo: "/images/IMG_3052.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a UBC engineering student interested in software, digital logic design, computers, hardware, and mechatronics. 
  <br><br>
  <a href="projects">Projects</a>
  <br><br>
  <a href="about">About Me</a>
  <br><br>
  <a href="contact">Contact</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
