title: Sophie Lin # your name (or website title) here
logo: "/images/IMG_3052.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a UBC mechanical engineering student specializing in Mechatronics. 
  <br>
  <a href="about.md">More about me</a><br>
  <br>
  [sophie.lin@ubc.ca](mailto:sophie.lin@ubc.ca) 
  <br><br>
  <a href="https://www.linkedin.com/in/sophie-lin-profile/">View My LinkedIn Profile</a><br>
  <a href="https://gitlab.com/slin14/">View My GitLab Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
